const {Router}=require('express');
const {authMiddleware}=require('../middleware/auth');
const {adminIPWhitelist,strictIPWhitelist}=require('../middleware/ipWhitelist');
const c=require('../controller/operationsController');
const {pool}=require('../config/db');
const {paginate}=require('../services/operations/data');
const router=Router();
router.use(authMiddleware,c.actor);
router.get('/case-options',(req,res)=>res.json({categories:c.categories,escalationCategories:c.escalationCategories}));
for(const kind of ['support','escalations']){
    const guards=kind==='escalations'?[adminIPWhitelist,c.requireStaff]:[(req,res,next)=>req.actor.roles.some(r=>['Admin','SuperAdmin'].includes(r))?adminIPWhitelist(req,res,next):next()];
    router.get(`/${kind}`,...guards,c.handler(req=>c.cases.list(req.actor,kind,req.query)));
    router.post(`/${kind}`,...guards,c.handler(req=>c.cases.create(req.actor,kind,req.body)));
    router.get(`/${kind}/:id`,...guards,c.handler(req=>c.cases.detail(req.actor,kind,req.params.id,req.query)));
    router.patch(`/${kind}/:id`,adminIPWhitelist,c.handler(req=>c.cases.update(req.actor,kind,req.params.id,req.body)));
    router.post(`/${kind}/:id/messages`,...guards,c.handler(req=>c.cases.message(req.actor,kind,req.params.id,req.body)));
}
router.use(adminIPWhitelist,c.requireStaff);
router.get('/overview',c.handler(()=>c.data.overview()));
router.get('/people',c.handler(req=>c.data.people(req.query)));
router.get('/people/:id',c.handler(req=>c.data.person(req.params.id,req.query.section,req.query)));
router.get('/universities',c.handler(()=>c.data.universities()));
router.get('/approvals/:kind',c.handler(req=>c.data.queue(req.params.kind,req.query)));
router.post('/approvals/videos/offering/:id/approve-pending',c.handler(req=>c.actions.approvePendingVideos(req.actor,req.params.id,req.body)));
router.post('/approvals/:kind/:id',c.handler(req=>c.actions.review(req.actor,req.params.kind,req.params.id,req.body)));
router.get('/transactions',c.handler(req=>c.data.transactions(req.query)));
router.get('/activity',c.handler(req=>c.data.auditLog(req.actor,req.query)));
router.use(c.requireOwner);
router.get('/catalogue',c.handler(req=>c.data.catalogue(req.query)));
router.get('/finance',c.handler(req=>c.data.finance(req.query)));
router.get('/security',c.handler(req=>paginate(pool,'s.id,s.title,s.description,s.severity,s.status,s.created_at','FROM security_updates s',[],req.query,'s.id DESC')));
router.post('/security',strictIPWhitelist,c.securityUpdate);
router.put('/security/:id/status',strictIPWhitelist,c.securityUpdate);
router.post('/admins',strictIPWhitelist,c.createAdmin);
router.put('/people/:id/role',strictIPWhitelist,c.changeRole);
router.put('/people/:id',strictIPWhitelist,c.updatePerson);
router.delete('/people/:id',strictIPWhitelist,c.deleteUser);
router.put('/catalogue/:id/price',strictIPWhitelist,c.price);
module.exports=router;
