// Synthetic local MySQL only; no dotenv, configured DB, provider/email, or credentials.
const test=require('node:test'),assert=require('node:assert/strict'),mysql=require('mysql2/promise'),fs=require('node:fs'),path=require('node:path'),express=require('express'),jwt=require('jsonwebtoken');
if(process.env.COURSE_WORKFLOW_ISOLATED_TEST!=='1')throw Error('Explicit local workflow fixture required');
process.env.JWT_SECRET='COURSE_WORKFLOW_SYNTHETIC';process.env.ADMIN_IP_WHITELIST_ENABLED='false';
let actual,pool,service,server,base,providerMode={},providerAdapter,connections=0,providerState='READY',blockReady,releaseReady,providerReads=0,failAudit=false,queries=[];
const inject=(file,value)=>{const f=require.resolve(file);require.cache[f]={id:f,filename:f,loaded:true,exports:value};};
function instrument(db,isConnection=false){return new Proxy(db,{get(t,k){if(k==='query')return async(sql,args)=>{assert.doesNotMatch(sql,/\b(CREATE|ALTER|DROP|TRUNCATE)\b/i);queries.push(sql);if(failAudit&&sql.startsWith('INSERT INTO admin_activity_log'))throw Error('SYNTHETIC_PRIVATE_ERROR');return t.query(sql,args);};if(k==='getConnection')return async()=>{connections++;return instrument(await t.getConnection(),true);};if(k==='release'&&isConnection)return()=>{connections--;t.release();};const value=t[k];return typeof value==='function'?value.bind(t):value;}});}
const readiness={async read(){providerReads++;assert.equal(connections,0,'No DB connection may wait for provider readiness');if(blockReady){blockReady=false;await new Promise(r=>releaseReady=r);}return {state:providerState,policyVerified:providerState==='READY'};}};
const actor=id=>({id,roles:['SuperAdmin']});
async function state(){return (await actual.query('SELECT * FROM course_workflows WHERE offering_id=1'))[0][0];}
async function token(id){const[[row]]=await actual.query('SELECT * FROM users WHERE id=?',[id]);return jwt.sign({id,roles:id===7?['Scholar']:id===3?['Admin']:id===4?['SuperAdmin']:['Learner'],purpose:'access',session:require('../src/utils/authSecurity').credentialBinding(row)},process.env.JWT_SECRET,{expiresIn:'1h'});}
async function http(route,id=7,method='GET',body){const r=await fetch(base+route,{method,headers:{...(id?{Authorization:'Bearer '+await token(id)}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};}
const deny=(work,status)=>assert.rejects(work,e=>e.status===status);
async function submit(){return service.transition(actor(7),1,'submit');}
async function publish(){return service.transition(actor(3),1,'publish',{confirmation:'PUBLISH COURSE 1',count:2});}
test.before(async()=>{
 const config={host:'127.0.0.1',port:33316,user:'root',password:'',database:'uniclips_course_workflow_test'};
 const admin=await mysql.createConnection({...config,database:undefined});await admin.query('CREATE DATABASE IF NOT EXISTS uniclips_course_workflow_test');await admin.end();actual=mysql.createPool({...config,connectionLimit:8});assert.equal((await actual.query('SELECT DATABASE() AS name'))[0][0].name,config.database);
 await actual.query('SET FOREIGN_KEY_CHECKS=0');const[tables]=await actual.query('SHOW TABLES');for(const row of tables){const name=Object.values(row)[0];assert.match(name,/^[a-z_]+$/);await actual.query('DROP TABLE '+name);}await actual.query('SET FOREIGN_KEY_CHECKS=1');
 for(const sql of [
 'CREATE TABLE users(id INT PRIMARY KEY,password VARCHAR(255),refresh_token VARCHAR(500),refresh_token_expires DATETIME,last_activity DATETIME,locked_until DATETIME,two_factor_enabled TINYINT,two_factor_secret VARCHAR(255),fname VARCHAR(30),lname VARCHAR(30))',
 'CREATE TABLE roles(id INT PRIMARY KEY,name VARCHAR(30))','CREATE TABLE user_roles(user_id INT,role_id INT)',
 'CREATE TABLE subjects(id INT PRIMARY KEY,name VARCHAR(100),bundle_price DECIMAL(10,2))','CREATE TABLE scholar_profile(user_id INT PRIMARY KEY,approved TINYINT)',
 'CREATE TABLE scholar_subjects(id INT PRIMARY KEY,subject_id INT,scholar_user_id INT,approved TINYINT)',
 'CREATE TABLE videos(id INT AUTO_INCREMENT PRIMARY KEY,subject_id INT,scholar_user_id INT,sequence_index INT,approved TINYINT DEFAULT 0,is_free TINYINT,title VARCHAR(200),description TEXT,price DECIMAL(10,2),video_url TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP)',
 'CREATE TABLE subject_purchases(id INT PRIMARY KEY,buyer_user_id INT,subject_id INT,scholar_id INT,created_at DATETIME,renewed_at DATETIME,access_expires_at DATETIME,is_access_active TINYINT)',
 'CREATE TABLE admin_activity_log(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,action VARCHAR(100),target_type VARCHAR(50),target_id INT,details JSON,created_at DATETIME DEFAULT CURRENT_TIMESTAMP)'
 ])await actual.query(sql);
 await actual.query("INSERT INTO roles VALUES(1,'Learner'),(2,'Admin'),(3,'SuperAdmin'),(4,'Scholar')");for(const id of [1,3,4,7,8]){await actual.query("INSERT INTO users VALUES(?, 'SYNTHETIC_HASH',?,DATE_ADD(NOW(),INTERVAL 1 DAY),NOW(),NULL,0,NULL,'Synthetic','User')",[id,'sha256:'+'1'.repeat(64)]);await actual.query('INSERT INTO user_roles VALUES(?,?)',[id,id===3?2:id===4?3:id>=7?4:1]);}
 await actual.query("INSERT INTO subjects VALUES(10,'Synthetic course',6),(20,'Other course',6)");await actual.query('INSERT INTO scholar_profile VALUES(7,1),(8,1)');await actual.query('INSERT INTO scholar_subjects VALUES(1,10,7,1),(2,20,8,1)');
 for(const sql of fs.readFileSync(path.join(__dirname,'../src/migrations/course_workflow_proposal.sql'),'utf8').split(';').map(x=>x.replace(/--[^\n]*/g,'').trim()).filter(Boolean))await actual.query(sql);
 pool=instrument(actual);inject('../src/config/db',{pool});providerAdapter=require('./fixtures/vimeoPolicy').syntheticVimeo({beforeRequest(){assert.equal(connections,0);},state:()=>providerMode});inject('../src/config/vimeo',{...providerAdapter,upload(file,opts,done){assert.equal(connections,0);assert.deepEqual(opts.privacy,{view:'nobody',embed:'private',download:false});providerAdapter.uploaded('/videos/900999',opts);done('/videos/900999');}});
 service=require('../src/services/courseWorkflow').createCourseWorkflow(pool,readiness);
 const app=express();app.use(express.json());app.use('/videos',require('../src/routes/videoRoutes'));app.use('/operations',require('../src/routes/operationsRoutes'));server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;
});
test.after(async()=>{if(server)await new Promise(r=>server.close(r));if(actual)await actual.end();});
test.beforeEach(async()=>{providerState='READY';providerMode={};providerAdapter.assets.clear();blockReady=false;releaseReady=null;failAudit=false;queries=[];providerReads=0;await actual.query('DELETE FROM user_roles WHERE user_id=7');await actual.query('INSERT INTO user_roles VALUES(7,4)');await actual.query('DELETE FROM course_workflow_uploads');await actual.query('DELETE FROM admin_activity_log');await actual.query('DELETE FROM videos');await actual.query('DELETE FROM subject_purchases');await actual.query("UPDATE course_workflows SET state='DRAFT',revision=0,legacy_published=0,feedback=NULL");await actual.query('UPDATE scholar_subjects SET approved=1');await actual.query('UPDATE scholar_profile SET approved=1');await actual.query("INSERT INTO videos(id,subject_id,scholar_user_id,sequence_index,approved,is_free,title,description,price,video_url) VALUES(101,10,7,1,0,1,'First','Synthetic',0,'https://vimeo.com/900101'),(102,10,7,2,0,0,'Second','Synthetic',1.25,'https://vimeo.com/900102')");});
test('new empty course is Draft; staff see Draft uploads before submission without publication',async()=>{assert.equal((await state()).state,'DRAFT');for(const id of [3,4]){const r=await http('/operations/course-workflows',id);assert.equal(r.status,200);assert.equal(r.body.rows[0].state,'DRAFT');assert.equal(r.body.rows[0].lesson_count,2);assert.equal((await http('/operations/course-workflows/1',id)).body.videos.length,2);}assert.equal((await http('/videos/101',1)).status,404);});
test('owner, live Scholar role and exact application required; client privileged roles grant nothing',async()=>{await deny(service.transition(actor(8),1,'submit'),403);await deny(service.transition(actor(1),1,'submit'),403);await actual.query('DELETE FROM user_roles WHERE user_id=7');await deny(submit(),403);assert.equal(providerReads,0);});
test('empty, malformed ordering and unusable media cannot be declared complete',async()=>{await actual.query('DELETE FROM videos');await deny(submit(),409);await actual.query("INSERT INTO videos(id,subject_id,scholar_user_id,sequence_index,title,description,video_url) VALUES(101,10,7,1,'Lesson','', 'https://vimeo.com/123'),(102,10,7,1,'Lesson','', 'https://vimeo.com/124')");await deny(submit(),409);await actual.query("UPDATE videos SET sequence_index=2,video_url='https://evil.example/124' WHERE id=102");await deny(submit(),503);});
test('processing, failed and unknown readiness deny submission, without holding DB connections',async()=>{for(const value of ['PROCESSING','FAILED','UNKNOWN']){providerState=value;await deny(submit(),409);assert.equal((await state()).state,'DRAFT');}});
test('explicit submission locks whole course and records actor/time/history without provider data',async()=>{assert.equal((await submit()).state,'SUBMITTED_FOR_REVIEW');const row=await state();assert.equal(row.submitted_by,7);assert.ok(row.submitted_at);const [logs]=await actual.query('SELECT * FROM admin_activity_log');assert.equal(logs[0].action,'COURSE_SUBMIT');assert.doesNotMatch(JSON.stringify(logs),/vimeo|900101|token/);assert.equal((await http('/videos/scholar/courses/10')).body.editable,false);});
test('Draft Move Up/Down, metadata edit and UniClips-only removal remain real route operations',async()=>{for(const ids of [[102,101],[101,102]])assert.equal((await http('/videos/scholar/courses/10/order',7,'PUT',{videoIds:ids})).status,200);assert.equal((await http('/videos/my/101',7,'PATCH',{title:'Corrected',description:'Updated'})).status,200);assert.equal((await http('/videos/my/102',7,'DELETE')).status,200);assert.equal((await http('/operations/course-workflows/1',3)).body.videos.length,1);assert.equal(providerReads,0);});
test('submitted upload admission, deletion, reorder and protected edit deny direct API bypass',async()=>{await submit();for(const [route,method,body] of [['/videos?subjectId=10','POST',{}],['/videos/my/101','DELETE'],['/videos/my/101','PATCH',{title:'Attack',description:''}],['/videos/scholar/courses/10/order','PUT',{videoIds:[102,101]}]])assert.equal((await http(route,7,method,body)).status,409);assert.equal((await http('/videos/scholar/courses/10')).status,200);assert.equal((await http('/videos/101',1)).status,404);});
test('Draft upload accepts transfer without claiming playback, without provider DELETE or long connection',async()=>{const form=new FormData();form.append('title','Third');form.append('description','Synthetic');form.append('subjectId','10');form.append('video',new Blob([require('./fixtures/uploadFiles').mp4],{type:'video/mp4'}),'synthetic.mp4');const r=await fetch(base+'/videos?subjectId=10',{method:'POST',headers:{Authorization:'Bearer '+await token(7)},body:form});assert.equal(r.status,201);const body=await r.json();assert.equal(body.uploadAccepted,true);assert.doesNotMatch(body.message,/ready|playable/i);assert.equal((await actual.query('SELECT COUNT(*) AS n FROM course_workflow_uploads'))[0][0].n,0);});
test('request changes requires feedback, persists it, unlocks corrections and resubmission relocks',async()=>{await submit();await deny(service.transition(actor(3),1,'request-changes',{reason:'bad'}),400);await service.transition(actor(3),1,'request-changes',{reason:'Please clarify the second lesson.'});assert.equal((await state()).feedback,'Please clarify the second lesson.');assert.equal((await http('/videos/my/102',7,'PATCH',{title:'Clarified',description:''})).status,200);await submit();assert.equal((await state()).state,'SUBMITTED_FOR_REVIEW');assert.equal((await http('/videos/my/101',7,'DELETE')).status,409);const[log]=await actual.query('SELECT action FROM admin_activity_log ORDER BY id');assert.deepEqual(log.map(r=>r.action),['COURSE_SUBMIT','COURSE_REQUEST_CHANGES','COURSE_SUBMIT']);});
test('SuperAdmin reopen requires current DB authority/reason and never mutates provider',async()=>{await submit();await deny(service.transition(actor(3),1,'reopen',{reason:'Reviewed exception'}),403);await service.transition(actor(4),1,'reopen',{reason:'Reviewed exception for clarification'});assert.equal((await state()).state,'CHANGES_REQUESTED');});
test('publication requires submitted state, exact confirmation and entire lesson count',async()=>{await deny(publish(),409);await submit();await deny(service.transition(actor(3),1,'publish',{confirmation:'PUBLISH COURSE 1',count:1}),400);await publish();assert.equal((await state()).state,'PUBLISHED');assert.deepEqual((await actual.query('SELECT approved FROM videos ORDER BY id'))[0].map(r=>r.approved),[1,1]);});
test('published complete course first is authenticated free, paid lesson exact entitlement, no client flags',async()=>{await submit();await publish();assert.equal((await http('/videos/101',0)).status,401);assert.equal((await http('/videos/101',1)).status,200);assert.equal((await http('/videos/102?isPurchased=true&userId=3&role=SuperAdmin',1)).status,403);await actual.query('INSERT INTO subject_purchases VALUES(1,1,10,7,NOW(),NULL,DATE_ADD(NOW(),INTERVAL 5 MONTH),1)');assert.equal((await http('/videos/102',1)).status,200);await actual.query('UPDATE subject_purchases SET access_expires_at=NOW()');assert.equal((await http('/videos/102',1)).status,403);});
test('Published Scholar operations remain locked; staff review does not itself publish',async()=>{await submit();assert.equal((await http('/operations/course-workflows/1',3)).status,200);assert.equal((await state()).state,'SUBMITTED_FOR_REVIEW');await publish();assert.equal((await http('/videos/my/101',7,'DELETE')).status,409);assert.equal((await http('/videos/my/102',7,'PATCH',{title:'Changed',description:''})).status,409);});
test('all unpublished workflow states deny learner regardless of video approved/client flag',async()=>{await actual.query('UPDATE videos SET approved=1');for(const s of ['DRAFT','SUBMITTED_FOR_REVIEW','CHANGES_REQUESTED']){await actual.query('UPDATE course_workflows SET state=? WHERE offering_id=1',[s]);assert.equal((await http('/videos/101?published=true',1)).status,404);assert.equal((await http('/videos/101',7)).status,200);assert.equal((await http('/videos/101',3)).status,200);}});
test('durable upload reservation and ambiguous transfer prohibit course submission',async()=>{await require('../src/utils/courseContent').withCourseLock(pool,7,10,db=>service.reserve(db,7,10,100));await deny(submit(),409);const[[row]]=await actual.query('SELECT * FROM course_workflow_uploads');await service.ambiguous({id:row.id});await deny(submit(),409);assert.equal((await actual.query('SELECT state FROM course_workflow_uploads'))[0][0].state,'RECONCILIATION_REQUIRED');});
test('concurrent submission has at most one commit and one audit event',async()=>{const results=await Promise.allSettled([submit(),submit()]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await actual.query("SELECT COUNT(*) AS n FROM admin_activity_log WHERE action='COURSE_SUBMIT'"))[0][0].n,1);});
test('reorder during readiness causes stale submission to deny without locking the DB over provider wait',async()=>{blockReady=true;const pending=submit();while(!releaseReady)await new Promise(r=>setTimeout(r,2));assert.equal((await http('/videos/scholar/courses/10/order',7,'PUT',{videoIds:[102,101]})).status,200);releaseReady();await deny(pending,409);assert.equal((await state()).state,'DRAFT');});
test('delete during readiness causes stale submission to deny and review listing loses reference',async()=>{blockReady=true;const pending=submit();while(!releaseReady)await new Promise(r=>setTimeout(r,2));assert.equal((await http('/videos/my/102',7,'DELETE')).status,200);releaseReady();await deny(pending,409);assert.equal((await http('/operations/course-workflows/1',3)).body.videos.length,1);});
test('upload reservation during readiness prevents stale submission finalization',async()=>{blockReady=true;const pending=submit();while(!releaseReady)await new Promise(r=>setTimeout(r,2));await require('../src/utils/courseContent').withCourseLock(pool,7,10,db=>service.reserve(db,7,10,100));releaseReady();await deny(pending,409);});
test('request changes racing publication cannot commit both transitions',async()=>{await submit();const results=await Promise.allSettled([publish(),service.transition(actor(3),1,'request-changes',{reason:'Please improve explanation'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.ok(['PUBLISHED','CHANGES_REQUESTED'].includes((await state()).state));});
test('audit failure rolls back state and all publication approval writes',async()=>{await submit();failAudit=true;await assert.rejects(publish());assert.equal((await state()).state,'SUBMITTED_FOR_REVIEW');assert.deepEqual((await actual.query('SELECT approved FROM videos'))[0].map(r=>r.approved),[0,0]);});
test('legacy per-video and pending-only publication aliases fail closed without changing prices',async()=>{for(const route of ['/operations/approvals/videos/101','/operations/approvals/videos/offering/1/approve-pending'])assert.equal((await http(route,3,'POST',{decision:'approve',price:999,confirmation:'APPROVE 2 VIDEOS #1'})).status,409);assert.equal((await actual.query('SELECT price FROM videos WHERE id=102'))[0][0].price,'1.25');});
test('review readiness auth is own/staff only; no provider credential or raw failure reaches response',async()=>{assert.equal((await http('/videos/101/readiness',0)).status,401);assert.equal((await http('/videos/101/readiness',1)).status,404);const r=await http('/videos/101/readiness',3);assert.equal(r.status,200);assert.equal(r.body.state,'READY');assert.doesNotMatch(JSON.stringify(r.body),/access_token|client_secret|files|password/);});
test('normal workflow/startup paths execute no DDL and no provider mutation is mounted',async()=>{await submit();await service.transition(actor(3),1,'request-changes',{reason:'Synthetic review feedback'});assert.ok(queries.length);assert.ok(queries.every(q=>!/^\s*(CREATE|ALTER|DROP)/i.test(q)));assert.doesNotMatch(fs.readFileSync(path.join(__dirname,'../src/services/videoReadiness.js'),'utf8'),/method:\s*['"](?:DELETE|POST|PATCH|PUT)/);assert.doesNotMatch(fs.readFileSync(path.join(__dirname,'../src/index.js'),'utf8'),/course_workflow_proposal/);});

test('actual submit and publication routes deny Public policy even when processing is complete',async()=>{
 providerMode={public:true};assert.equal((await http('/videos/scholar/courses/10/submit',7,'POST',{})).status,409);assert.equal((await state()).state,'DRAFT');
 providerMode={};assert.equal((await http('/videos/scholar/courses/10/submit',7,'POST',{})).status,200);
 providerMode={public:true};assert.equal((await http('/operations/course-workflows/1/publish',3,'POST',{confirmation:'PUBLISH COURSE 1',count:2})).status,409);
 assert.equal((await state()).state,'SUBMITTED_FOR_REVIEW');assert.deepEqual((await actual.query('SELECT approved FROM videos'))[0].map(r=>r.approved),[0,0]);
});
test('Draft review and direct lesson routes fail closed on incorrect owner, Public policy or processing',async()=>{
 for(const mode of [{wrongOwner:true},{public:true},{processing:true},{failure:403},{failure:429},{failure:500}]){
  providerMode=mode;const review=await http('/videos/101/readiness',3);assert.equal(review.body.player_url,undefined);assert.notEqual(review.body.state,'READY');
  const direct=await http('/videos/101',7);assert.equal(direct.status,503);assert.equal(direct.body.player_url,undefined);
 }
});
test('resubmission rechecks policy; a forged READY-only reader cannot certify publication',async()=>{
 await submit();await service.transition(actor(3),1,'request-changes',{reason:'Please clarify the second lesson.'});
 providerMode={public:true};assert.equal((await http('/videos/scholar/courses/10/submit',7,'POST',{})).status,409);assert.equal((await state()).state,'CHANGES_REQUESTED');
 const uncertified=require('../src/services/courseWorkflow').createCourseWorkflow(pool,{async read(){return {state:'READY'};}});
 await deny(uncertified.transition(actor(7),1,'submit'),409);
});
test('failed upload policy preserves durable reservation across service restart and prevents duplicate submission',async()=>{
 providerMode={failure:500};const form=new FormData();form.append('title','Private');form.append('description','Synthetic');form.append('video',new Blob([require('./fixtures/uploadFiles').mp4],{type:'video/mp4'}),'synthetic.mp4');
 const response=await fetch(base+'/videos?subjectId=10',{method:'POST',headers:{Authorization:'Bearer '+await token(7)},body:form});assert.equal(response.status,503);const body=await response.json();
 assert.equal(body.videoUrl,undefined);assert.doesNotMatch(JSON.stringify(body),/SYNTHETIC_PROVIDER_SECRET/);assert.equal((await actual.query('SELECT COUNT(*) AS n FROM videos'))[0][0].n,2);
 const reservations=(await actual.query('SELECT * FROM course_workflow_uploads'))[0];assert.equal(reservations.length,1);assert.equal(reservations[0].state,'RECONCILIATION_REQUIRED');
 assert.equal(providerAdapter.asset(900999).privacy.view,'nobody');providerMode={};
 const restarted=require('../src/services/courseWorkflow').createCourseWorkflow(pool,readiness);await deny(restarted.transition(actor(7),1,'submit'),409);
});
test('legacy Published state and approvals are preserved when policy drift blocks playback',async()=>{
 await actual.query("UPDATE course_workflows SET state='PUBLISHED',legacy_published=1 WHERE offering_id=1");await actual.query('UPDATE videos SET approved=1');
 const before=(await actual.query('SELECT id,approved,video_url FROM videos ORDER BY id'))[0];providerMode={public:true};
 assert.equal((await http('/videos/101',1)).status,503);assert.equal((await state()).state,'PUBLISHED');assert.equal((await state()).legacy_published,1);
 assert.deepEqual((await actual.query('SELECT id,approved,video_url FROM videos ORDER BY id'))[0],before);
});
