// Actual installed mysql2, existing local MySQL CA, loopback-only TCP fixtures.
// Never reads dotenv, connects to production, generates a CA or writes SQL.
const test = require('node:test');
const assert = require('node:assert/strict');
const net = require('node:net');
const tls = require('node:tls');
const crypto = require('node:crypto');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const mysql = require('mysql2/promise');
const { buildPoolConfig, verifyDatabaseConnection } = require('../src/config/databaseTls');
const driverRoot = path.dirname(require.resolve('mysql2/package.json'));
const Handshake = require(path.join(driverRoot, 'lib/packets/handshake'));

const u24 = n => Buffer.from([n >> 16 & 255, n >> 8 & 255, n & 255]);
const u16 = n => { const b = Buffer.alloc(2); b.writeUInt16BE(n); return b; };

async function fakeServer(t, mode) {
  const sockets = new Set(); const evidence = { attempts: 0, incomingBytes: 0 };
  const server = net.createServer(socket => {
    evidence.attempts++; sockets.add(socket);
    socket.on('error', () => {}); socket.on('close', () => sockets.delete(socket));
    const hello = new Handshake({ protocolVersion: 10, serverVersion: '8.0-isolated',
      connectionId: 1, capabilityFlags: 1 | 512 | 32768 | 524288 | (mode === 'noTLS' ? 0 : 2048),
      characterSet: 45, statusFlags: 2, authPluginData1: Buffer.alloc(8, 1), authPluginData2: Buffer.alloc(12, 2) });
    const packet = hello.toPacket(0); packet.writeHeader(0); socket.write(packet.buffer);
    let received = Buffer.alloc(0), responded = false;
    socket.on('data', chunk => {
      evidence.incomingBytes += chunk.length; received = Buffer.concat([received, chunk]);
      if (mode === 'noTLS' || responded || received.length <= 36 || received[36] !== 22) return;
      responded = true;
      // A MySQL SSLRequest followed by a real ClientHello. Send an invalid DER
      // certificate in a TLS 1.2 Certificate message; no cert/key is generated.
      const serverHello = Buffer.concat([Buffer.from([3, 3]), crypto.randomBytes(32), Buffer.from([0, 0xc0, 0x2b, 0])]);
      const certificate = Buffer.concat([u24(6), u24(3), Buffer.from([1, 2, 3])]);
      const messages = Buffer.concat([Buffer.from([2]), u24(serverHello.length), serverHello,
        Buffer.from([11]), u24(certificate.length), certificate]);
      socket.write(Buffer.concat([Buffer.from([22, 3, 3]), u16(messages.length), messages]));
    });
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(async () => { for (const socket of sockets) socket.destroy(); await new Promise(resolve => server.close(resolve)); });
  return { port: server.address().port, evidence };
}

test('installed mysql2 enforces verified TLS with loopback fixtures', { skip: process.env.DB_TLS_ISOLATED_TEST !== '1' }, async t => {
  // These are existing test-container certificates, not the production CA.
  // Contents stay in memory and never enter assertions, reports or Git files.
  const read = file => execFileSync('docker', ['exec', 'uniclips-payment-phase2a-test', 'cat', `/var/lib/mysql/${file}`], { stdio: ['ignore', 'pipe', 'pipe'] });
  // MySQL's autogenerated fixture PEM includes a trailing NUL. Normalize only
  // this test input; production files with non-PEM bytes still fail validation.
  const ca = Buffer.from(read('ca.pem').toString('utf8').replace(/\0+$/, ''));
  const certificate = new crypto.X509Certificate(read('server-cert.pem'));
  const hostname = certificate.subject.match(/(?:^|\n)CN=(.+)/)[1];
  const env = { NODE_ENV: 'production', DB_HOST: hostname, DB_USER: 'root', DB_NAME: 'mysql', DB_PORT: '33316', DB_SSL: 'true', DB_SSL_CA: '/existing-isolated/ca.pem' };
  const target = { host: '127.0.0.1', port: 33316 };
  function poolFor(options, destination = target) {
    const evidence = { attempts: 0 };
    const pool = mysql.createPool({ ...options, connectTimeout: 3000,
      stream: () => { evidence.attempts++; return net.connect(destination.port, destination.host); } });
    return { pool, evidence };
  }

  await t.test('trusted existing CA and matching hostname establish actual TLS; same-session SHOW confirms it', async t => {
    const config = buildPoolConfig(env, () => ca), { pool } = poolFor(config); t.after(() => pool.end());
    const logs = []; await verifyDatabaseConnection(pool, config, { log: s => logs.push(s) });
    const connection = await pool.getConnection();
    try {
      assert.equal(connection.connection.stream.authorized, true);
      assert.ok(/^TLSv1\.[23]$/.test(connection.connection.stream.getProtocol()));
    } finally { connection.release(); }
    assert.deepEqual(logs, ['Database connection established with TLS']);
  });

  await t.test('untrusted CA is rejected by real mysql2; no plaintext retry', async t => {
    const config = buildPoolConfig(env, () => Buffer.from(tls.rootCertificates[0]));
    const { pool, evidence } = poolFor(config); t.after(() => pool.end());
    await assert.rejects(pool.getConnection(), { code: 'HANDSHAKE_SSL_ERROR' });
    assert.equal(evidence.attempts, 1);
  });

  await t.test('trusted CA with mismatching hostname is rejected by real mysql2', async t => {
    const config = buildPoolConfig({ ...env, DB_HOST: 'wrong-host.example.invalid' }, () => ca);
    const { pool, evidence } = poolFor(config); t.after(() => pool.end());
    await assert.rejects(pool.getConnection(), { code: 'HANDSHAKE_SSL_ERROR' });
    assert.equal(evidence.attempts, 1);
  });

  await t.test('server with no TLS support receives no credentials and cannot fulfil startup', async t => {
    const fake = await fakeServer(t, 'noTLS'), config = buildPoolConfig(env, () => ca);
    const { pool, evidence } = poolFor(config, { host: '127.0.0.1', port: fake.port }); t.after(() => pool.end());
    await assert.rejects(pool.getConnection(), { code: 'HANDSHAKE_NO_SSL_SUPPORT' });
    assert.equal(evidence.attempts, 1); assert.equal(fake.evidence.incomingBytes, 0);
  });

  await t.test('invalid peer certificate aborts the TLS handshake; no retry', async t => {
    const fake = await fakeServer(t, 'invalidCertificate'), config = buildPoolConfig(env, () => ca);
    config.ssl.maxVersion = 'TLSv1.2';
    const { pool, evidence } = poolFor(config, { host: '127.0.0.1', port: fake.port }); t.after(() => pool.end());
    await assert.rejects(pool.getConnection(), { code: 'HANDSHAKE_SSL_ERROR' });
    assert.equal(evidence.attempts, 1);
  });
});
