// Guarded loopback MySQL, synthetic accounts, forbidden provider doubles. No .env.
const test=require('node:test'),assert=require('node:assert/strict'),mysql=require('mysql2/promise'),jwt=require('jsonwebtoken'),express=require('express');
if(process.env.P1D_ISOLATED_TEST!=='1')throw Error('Explicit isolated P1D test flag required');
process.env.JWT_SECRET='P1D_SYNTHETIC_SIGNING_KEY';
const config={host:'127.0.0.1',port:33316,user:'root',password:'',database:'uniclips_content_p1d_test'};
let actual,pool,service,server,base,queries=[],failEntitlement=false,failRoles=false;
const inject=(file,exports)=>{const f=require.resolve(file);require.cache[f]={id:f,filename:f,loaded:true,exports};};
function instrument(db){return new Proxy(db,{get(target,key){if(key==='query')return async(sql,args)=>{queries.push({sql,args});assert.doesNotMatch(sql,/\b(CREATE|ALTER|DROP|TRUNCATE)\b/i);if(failEntitlement&&sql.includes('FROM subject_purchases'))throw Error('SYNTHETIC_PRIVATE_SQL');if(failRoles&&sql.startsWith('SELECT r.name'))throw Error('SYNTHETIC_PRIVATE_SQL');return target.query(sql,args);};if(key==='getConnection')return async()=>instrument(await target.getConnection());const value=target[key];return typeof value==='function'?value.bind(target):value;}});}
const actor=(id=1,roles=['Learner'])=>({id,roles});
async function token(id=1,roles=['Learner']){const[[row]]=await actual.query('SELECT * FROM users WHERE id=?',[id]);return jwt.sign({id,roles,purpose:'access',session:require('../src/utils/authSecurity').credentialBinding(row)},process.env.JWT_SECRET,{expiresIn:'1h'});}
async function request(route,id=1,roles=['Learner'],body){return fetch(base+route,{method:body?'POST':'GET',headers:{...(id?{Authorization:'Bearer '+await token(id,roles)}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});}
const deny=async(promise,status)=>assert.rejects(promise,e=>e.status===status);
async function entitlement(buyer=1,changes=''){await actual.query(`INSERT INTO subject_purchases(buyer_user_id,subject_id,scholar_id,created_at,access_expires_at,is_access_active) VALUES (?,10,7,DATE_SUB(NOW(),INTERVAL 1 MONTH),DATE_ADD(DATE_SUB(NOW(),INTERVAL 1 MONTH),INTERVAL 5 MONTH),1)`,[buyer]);if(changes)await actual.query('UPDATE subject_purchases SET '+changes);}
test.before(async()=>{
 const admin=await mysql.createConnection({...config,database:undefined});await admin.query('CREATE DATABASE IF NOT EXISTS uniclips_content_p1d_test');await admin.end();actual=mysql.createPool({...config,connectionLimit:6});assert.equal((await actual.query('SELECT DATABASE() AS name'))[0][0].name,config.database);
 for(const name of ['course_workflow_uploads','course_workflows','user_library','video_progress','purchases','subject_purchases','videos','scholar_subjects','scholar_profile','subjects','universities','user_roles','roles','users'])await actual.query('DROP TABLE IF EXISTS '+name);
 for(const sql of [
 'CREATE TABLE users(id INT PRIMARY KEY,fname VARCHAR(100),lname VARCHAR(100),email VARCHAR(100),password VARCHAR(255),refresh_token VARCHAR(500),refresh_token_expires DATETIME,last_activity DATETIME,locked_until DATETIME,two_factor_enabled TINYINT,two_factor_secret VARCHAR(255))',
 'CREATE TABLE roles(id INT PRIMARY KEY,name VARCHAR(30))','CREATE TABLE user_roles(user_id INT,role_id INT)',
 'CREATE TABLE universities(id INT PRIMARY KEY,name VARCHAR(100),short_name VARCHAR(20))',
 'CREATE TABLE subjects(id INT PRIMARY KEY,name VARCHAR(100),bundle_price DECIMAL(10,2),degree_programmes VARCHAR(100),university_id INT)',
 'CREATE TABLE scholar_profile(user_id INT PRIMARY KEY,approved TINYINT,university VARCHAR(100),degree VARCHAR(100))',
 'CREATE TABLE scholar_subjects(id INT PRIMARY KEY,subject_id INT,scholar_user_id INT,approved TINYINT,expertise TEXT)',
 'CREATE TABLE videos(id INT PRIMARY KEY,subject_id INT,scholar_user_id INT,sequence_index INT,approved TINYINT,is_free TINYINT,title VARCHAR(100),description TEXT,price DECIMAL(10,2),video_url TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP)',
 'CREATE TABLE subject_purchases(id INT AUTO_INCREMENT PRIMARY KEY,buyer_user_id INT,subject_id INT,scholar_id INT,created_at DATETIME,renewed_at DATETIME,access_expires_at DATETIME,is_access_active TINYINT)',
 'CREATE TABLE purchases(id INT PRIMARY KEY,buyer_user_id INT,video_id INT,amount DECIMAL(10,2))',
 'CREATE TABLE user_library(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,subject_id INT,scholar_id INT,added_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,subject_id,scholar_id))',
 'CREATE TABLE video_progress(user_id INT,video_id INT,progress_seconds INT,watched TINYINT,watched_at DATETIME,PRIMARY KEY(user_id,video_id))'
 ])await actual.query(sql);
 await actual.query("INSERT INTO roles VALUES(1,'Learner'),(2,'Admin'),(3,'SuperAdmin'),(4,'Scholar')");
 for(const id of [1,2,3,4,7,8]){await actual.query('INSERT INTO users VALUES(?,?,?, ?,?,?,DATE_ADD(NOW(),INTERVAL 1 DAY),NOW(),NULL,0,NULL)',[id,'Synthetic','User',`content${id}@example.invalid`,'SYNTHETIC_HASH','sha256:'+'1'.repeat(64)]);await actual.query('INSERT INTO user_roles VALUES(?,?)',[id,id===3?2:id===4?3:id>=7?4:1]);}
 await actual.query("INSERT INTO universities VALUES(1,'Synthetic University','SYN')");await actual.query("INSERT INTO subjects VALUES(10,'Course One',6,'Synthetic programme',1),(20,'Course Two',6,'Synthetic programme',1)");await actual.query('INSERT INTO scholar_profile(user_id,approved) VALUES(7,1),(8,1)');await actual.query('INSERT INTO scholar_subjects VALUES(1,10,7,1,NULL),(2,20,8,0,NULL)');
 for(const [id,subject,scholar,sequence,approved]of [[101,10,7,2,1],[102,10,7,7,1],[103,10,7,9,0],[201,20,8,1,1],[202,20,8,2,1]])await actual.query('INSERT INTO videos(id,subject_id,scholar_user_id,sequence_index,approved,is_free,title,video_url) VALUES(?,?,?,?,?,1,?,?)',[id,subject,scholar,sequence,approved,'Synthetic lesson','https://vimeo.com/'+(900000+id)]);
 for(const sql of require('node:fs').readFileSync(require('node:path').join(__dirname,'../src/migrations/course_workflow_proposal.sql'),'utf8').split(';').map(x=>x.replace(/--[^\n]*/g,'').trim()).filter(Boolean))await actual.query(sql);
 pool=instrument(actual);inject('../src/config/db',{pool});inject('../src/config/stripe',new Proxy({},{get(){throw Error('Provider operations forbidden');}}));inject('../src/config/vimeo',require('./fixtures/vimeoPolicy').syntheticVimeo({beforeRequest(o){assert.equal(o.method,'GET','P1-D playback never changes provider policy');}}));
 service=require('../src/services/contentAuthorization').createContentAuthorization(pool);
 const app=express();app.use(express.json());app.use('/videos',require('../src/routes/videoRoutes'));app.use('/library',require('../src/routes/libraryRoutes'));server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});base='http://127.0.0.1:'+server.address().port;
});
test.after(async()=>{if(server)await new Promise(resolve=>server.close(resolve));if(actual)await actual.end();});
test.beforeEach(async()=>{await actual.query("UPDATE course_workflows SET state='PUBLISHED',legacy_published=1 WHERE offering_id=1");queries=[];failEntitlement=false;failRoles=false;await actual.query('DELETE FROM subject_purchases');await actual.query('DELETE FROM purchases');await actual.query('UPDATE scholar_profile SET approved=1');await actual.query('UPDATE scholar_subjects SET approved=IF(id=1,1,0)');await actual.query('UPDATE videos SET approved=IF(id=103,0,1),sequence_index=CASE id WHEN 101 THEN 2 WHEN 102 THEN 7 WHEN 103 THEN 9 WHEN 201 THEN 1 ELSE 2 END');});
test('anonymous free and paid direct routes and course learning metadata require login',async()=>{for(const path of ['/videos/101','/videos/102','/videos/watch/101','/videos/watch/102','/videos/courses/10/7','/videos/subject/10?scholarId=7'])assert.equal((await request(path,0)).status,401);});
test('authenticated first real sequence lesson is free despite non-contiguous sequence',async()=>{const r=await service.playback(actor(),101,10,7);assert.equal(r.video.can_access,true);assert.equal(r.video.is_first_preview,true);assert.equal(r.video.player_url,'https://player.vimeo.com/video/900101');});
test('client is_free flag cannot grant the second lesson',async()=>{await deny(service.playback(actor(),102),403);assert.equal((await request('/videos/watch/102?isPurchased=true&purchased=true&is_free=true&userId=2&role=SuperAdmin')).status,403);});
test('active course purchase permits paid lesson with media-only projection',async()=>{await entitlement();const r=await service.playback(actor(),102,10,7);assert.equal(r.hasPurchased,true);assert.equal(r.video.can_access,true);assert.equal(r.video.video_url,undefined);assert.equal(r.video.scholar_email,undefined);});
test('stale client entitlement and signed role hints are rechecked on every request',async()=>{await entitlement();assert.equal((await request('/videos/watch/102')).status,200);await actual.query('UPDATE subject_purchases SET access_expires_at=DATE_SUB(NOW(),INTERVAL 1 SECOND)');assert.equal((await request('/videos/watch/102?isPurchased=true',1,['SuperAdmin'])).status,403);});
test('legacy history response never restores a provider identifier',async()=>{await actual.query('INSERT INTO purchases VALUES(1,1,102,2)');const[rows]=await require('../src/models/purchases').PurchaseModel.findByUser(1);assert.equal(rows.length,1);assert.equal(rows[0].video_id,102);assert.equal(rows[0].video_url,undefined);assert.doesNotMatch(JSON.stringify(rows),/vimeo|player_url/);});
test('course metadata exposes access decisions without any player/provider identifier',async()=>{const r=await service.course(actor(),10,7);assert.deepEqual(r.videos.map(v=>v.can_access),[true,false]);assert.doesNotMatch(JSON.stringify(r),/vimeo|video_url|player_url|email|password/);});
test('another user purchase and client userId cannot grant entitlement',async()=>{await entitlement(2);await deny(service.playback(actor(),102),403);assert.equal((await request('/videos/watch/102?userId=2')).status,403);});
test('legacy unreconciled individual video purchase grants no course entitlement',async()=>{await actual.query('INSERT INTO purchases VALUES(1,1,102,2)');await deny(service.playback(actor(),102),403);assert.equal(queries.some(q=>/FROM purchases\b/.test(q.sql)),false);});
for(const [label,mutation]of [ ['expired','access_expires_at=DATE_SUB(NOW(),INTERVAL 1 SECOND)'],['disabled','is_access_active=0'],['null indefinite expiry','access_expires_at=NULL'],['future purchase','created_at=DATE_ADD(NOW(),INTERVAL 1 DAY)'],['longer than five calendar months','access_expires_at=DATE_ADD(created_at,INTERVAL 6 MONTH)'],['renewal before purchase','renewed_at=DATE_SUB(created_at,INTERVAL 1 DAY)'],['future renewal','renewed_at=DATE_ADD(NOW(),INTERVAL 1 DAY)'] ])test(label+' entitlement denies paid access',async()=>{await entitlement(1,mutation);await deny(service.playback(actor(),102),403);});
test('legitimate renewal uses existing renewed_at and remains five calendar months',async()=>{await entitlement(1,'created_at=DATE_SUB(NOW(),INTERVAL 8 MONTH),renewed_at=DATE_SUB(NOW(),INTERVAL 1 MONTH),access_expires_at=DATE_ADD(DATE_SUB(NOW(),INTERVAL 1 MONTH),INTERVAL 5 MONTH)');assert.equal((await service.playback(actor(),102)).hasPurchased,true);});
test('calendar month expiry uses MySQL clamping rather than a fixed-day duration',async()=>{const[[r]]=await actual.query("SELECT DATE_ADD('2026-01-31',INTERVAL 5 MONTH) AS expiry,DATE_ADD('2025-09-30',INTERVAL 5 MONTH) AS leapBoundary");assert.equal(String(r.expiry).slice(0,10),'2026-06-30');assert.equal(String(r.leapBoundary).slice(0,10),'2026-02-28');});
test('expired paid access still allows first free lesson',async()=>{await entitlement(1,'access_expires_at=DATE_SUB(NOW(),INTERVAL 1 DAY)');assert.equal((await service.playback(actor(),101)).video.can_access,true);});
test('cross-course and cross-Scholar lesson relationship mismatch denies even with purchase',async()=>{await entitlement();await deny(service.playback(actor(),102,20,7),404);await deny(service.playback(actor(),102,10,8),404);await deny(service.playback(actor(),202,10,7),404);});
test('client privileged role and owner claims do not replace current DB roles',async()=>{await deny(service.playback(actor(1,['SuperAdmin','Admin','Scholar']),103),404);await deny(service.playback(actor(1,['Admin']),102),403);});
test('own approved Scholar may preview own pending content, not another private offering',async()=>{assert.equal((await service.playback(actor(7),103)).ownerAccess,true);await deny(service.playback(actor(7),201),404);});
test('Admin and SuperAdmin retain legitimate private operational review',async()=>{for(const id of [3,4])assert.equal((await service.playback(actor(id),201)).operationalAccess,true);});
test('unpublished lesson and unapproved course/profile fail closed for learner',async()=>{await entitlement();await deny(service.playback(actor(),103),404);await deny(service.playback(actor(),201),404);await actual.query('UPDATE scholar_profile SET approved=0 WHERE user_id=7');await deny(service.playback(actor(),101),404);});
test('malformed/unknown account, lesson and course IDs never yield media',async()=>{for(const id of ['no',0,-1,'1.5',{},[],Number.MAX_SAFE_INTEGER+1])await deny(service.playback(actor(),id),400);await deny(service.playback(actor(),999),404);await deny(service.course(actor(),999,7),404);await deny(service.playback(actor(999),101),403);});
test('malformed or duplicate sequence cannot invent a free lesson',async()=>{await actual.query('UPDATE videos SET sequence_index=2 WHERE id=102');await deny(service.playback(actor(),101),404);await actual.query('UPDATE videos SET sequence_index=NULL WHERE id=102');await deny(service.playback(actor(),101),404);});
test('pending first lesson does not make a later paid lesson free',async()=>{await actual.query('UPDATE videos SET approved=0 WHERE id=101');await deny(service.playback(actor(),102),403);});
test('entitlement and role database errors return safe denial without metadata',async()=>{failEntitlement=true;const r=await request('/videos/watch/101');assert.equal(r.status,503);assert.deepEqual(await r.json(),{message:'Content is temporarily unavailable'});failEntitlement=false;failRoles=true;assert.equal((await request('/videos/watch/101')).status,503);});
test('public catalogue remains available and excludes all media/private identifiers',async()=>{const r=await request('/videos/all-videos',0);assert.equal(r.status,200);const body=await r.json();assert.deepEqual(body.videos.map(v=>v.id).sort(),[101,102]);assert.doesNotMatch(JSON.stringify(body),/vimeo|video_url|player_url|email|refresh|secret/);assert.equal(body.videos.find(v=>v.id===102).is_free,0);});
test('saved library is metadata only and never grants paid playback',async()=>{const r=await request('/library/add',1,['Learner'],{subjectId:10,scholarId:7,userId:2});assert.equal(r.status,200);const body=await(await request('/library/my-library')).json();assert.doesNotMatch(JSON.stringify(body),/vimeo|video_url|player_url/);await deny(service.playback(actor(),102),403);});
test('progress writes are authorized by real lesson and authenticated user only',async()=>{assert.equal((await request('/library/save-progress',1,['Learner'],{videoId:102,progressSeconds:12,userId:2})).status,403);assert.equal((await request('/library/save-progress',1,['Learner'],{videoId:101,progressSeconds:12,userId:2})).status,200);const[rows]=await actual.query('SELECT user_id FROM video_progress WHERE video_id=101');assert.deepEqual(rows.map(r=>r.user_id),[1]);});
test('player URI projection accepts approved Vimeo forms and rejects arbitrary providers',()=>{const{playerMetadata}=require('../src/services/contentAuthorization');assert.deepEqual(playerMetadata('https://vimeo.com/123456/abcdef123'),{player_url:'https://player.vimeo.com/video/123456?h=abcdef123'});for(const uri of ['http://vimeo.com/123','https://evil.example/123','https://vimeo.com.evil.example/123','https://owner@vimeo.com/123','https://vimeo.com/123#secret'])assert.throws(()=>playerMetadata(uri),e=>e.status===503);});
test('authorization request transactions contain zero DDL and use consistent read-only snapshots',async()=>{await service.playback(actor(),101);assert.ok(queries.some(q=>q.sql==='START TRANSACTION READ ONLY'));assert.ok(queries.every(q=>!/^\s*(INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)/i.test(q.sql)));});
